version: '3.8'

services:

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data
    networks:
      - corewallet-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - corewallet-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - corewallet-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@corewallet.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - corewallet-net

  mock-kyc:
    image: mockserver/mockserver
    container_name: mock-kyc
    ports:
      - "1080:1080"
    networks:
      - corewallet-net

  mock-bank:
    image: mockserver/mockserver
    container_name: mock-bank
    ports:
      - "1081:1080"
    networks:
      - corewallet-net

volumes:
  userdb_data:

networks:
  corewallet-net:
    driver: bridge
